apiVersion: v1
kind: Service
metadata:
  name: k8s_prediction_service
spec:
  selector:
    app: k8s_prediction
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 6000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s_prediction
spec:
  selector:
    matchLabels:
      app: k8s_prediction
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s_prediction
    spec:
      containers:
      - name: k8s_prediction
        image: k8s_prediction:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
