apiVersion: v1
kind: Service
metadata:
  name: k8s-prediction-service
spec:
  selector:
    app: k8s-prediction
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-prediction
spec:
  selector:
    matchLabels:
      app: k8s-prediction
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-prediction
    spec:
      containers:
      - name: k8s-prediction
        image: k8s-prediction:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
